### ISSUE TITLE
Flags for spawn/warzone

### ISSUE THREAD

**Issue by ErwanScraft** [ShockedPlot7560/FactionMaster#33]
Can you add a see chunk feature like piggyfactions .
And add flags like in piggy factions.

**Comment by ShockedPlot7560** [comment]
What do you mean by flags ?

**Comment by ShockedPlot7560** [comment]
For the chunk viewer, I can redirect you to an existing plugin: https://poggit.pmmp.io/p/ChunkBorders/1.0.0

**Comment by ShockedPlot7560** [comment]
I finally decided to implement this feature in the next big release.
This is simply due to the fact that, currently, the data storage format does not really allow for this implementation, and it would require far too many major changes for the current stable release.
Having a change to the data storage structure in the databases at v3.0.0, this will implement that fact.
Thanks for the suggestion!
It has been taken into account, it's just a matter of patience, I estimate v3.0.0 in two/three weeks at the most.

Translated with www.DeepL.com/Translator (free version)

**Comment by mesiiiiiii** [comment]
He means zones, warzone is the zone where players can fight, but not claim neither build. Spawn is a safe zone where players cant fight neither claim neither build. Wilderness is a zone where players can fight, claim and build.

**Comment by ShockedPlot7560** [comment]
This will be implemented in v3.0.0 normally
