### ISSUE TITLE
The database is not deleted

### ISSUE THREAD

**Issue by MrBlasyMSK** [ShockedPlot7560/FactionMaster#41]
Step 1: Create a faction
Step 2: Remove the plugin and plugin_data
Step 3: Enter the server and restart it when you have entered
Step 4: Put the plugin back (only the plugin, not the plugin_data)
Step 5: Login to the server and use / f

It will appear that your faction has the last name you entered, but it should reset everything completely and is storing it somewhere

**Comment by ShockedPlot7560** [comment]
If you want to delete the entire faction plugin data, in case the PROVIDER is set to SQLITE, you have to delete the file FactionMaster.sqlite in the server files. In case you put it on MYSQL, you have to empty the database.
I wouldn't put a total reuse system from the start because in case of bad manipulation, everything will be deleted. Maybe set up a command to reset everything, why not.

**Comment by MrBlasyMSK** [comment]
I think if it would be fine to add a command or something that can restart it because I have no idea how to do that xD

**Comment by ShockedPlot7560** [comment]
> I think if it would be fine to add a command or something that can restart it because I have no idea how to do that xD

What PROVIDER have you set in your config.yml ?

**Comment by MrBlasyMSK** [comment]
PROVIDER: "SQLITE"

**Comment by ShockedPlot7560** [comment]
you normally have a file called FactionMaster.sqlite in the pocketmine files, where the start.cmd etc is. You just have to delete this file when the server is closed, and restart it, it should recreate the structure automatically.

**Comment by MrBlasyMSK** [comment]
> you normally have a file called FactionMaster.sqlite in the pocketmine files, where the start.cmd etc is. You just have to delete this file when the server is closed, and restart it, it should recreate the structure automatically.

Ohhhhhhh, thx <3
