### ISSUE TITLE
Faction creation crash

### ISSUE THREAD

**Issue by Rtoxx** [ShockedPlot7560/FactionMaster#91]
Hey, when a person create a faction, the player is not in the faction, the faction exist but nobody is inside

 - Plugin installed= version 3.1.4

Error :  Exception: "SQLSTATE[HY000]: General error: 1 near ".": syntax error" (E_ERROR) in "plugins/FactionMaster-stable/src/ShockedPlot7560/FactionMaster/Task/DatabaseTask" at line 97
2021-12-18 [18:19:09] [Asynchronous Worker #1 thread/CRITICAL]: #0 pmsrc/src/pocketmine/scheduler/AsyncTask(85): ShockedPlot7560\FactionMaster\Task\DatabaseTask->onRun()
2021-12-18 [18:19:09] [Asynchronous Worker #1 thread/CRITICAL]: #1 (): pocketmine\scheduler\AsyncTask->run()
2021-12-18 [18:19:09] [Asynchronous Worker #0 thread/CRITICAL]: Exception: "SQLSTATE[HY000]: General error: 1 near ".": syntax error" (E_ERROR) in "plugins/FactionMaster-stable/src/ShockedPlot7560/FactionMaster/Task/DatabaseTask" at line 97
2021-12-18 [18:19:09] [Asynchronous Worker #0 thread/CRITICAL]: #0 pmsrc/src/pocketmine/scheduler/AsyncTask(85): ShockedPlot7560\FactionMaster\Task\DatabaseTask->onRun()

**Comment by ShockedPlot7560** [comment]
Can you send the step to reproduce the bug ? 
Which value to enter / which config etc

**Comment by Rtoxx** [comment]
/f , the ui open, create faction, you create your faction and you quit the ui and you are not in the faction

**Comment by ShockedPlot7560** [comment]
Have you special config, can you send the file without the database connection information ?

**Comment by RtoxGaming** [comment]
# DO NOT EDIT THIS VALUE. ONLY FOR INTERNAL USE.
file-version: 9
# DO NOT EDIT THIS VALUE. ONLY FOR INTERNAL USE.

# --------------------- DATABASE --------------------------

# Use only SQLITE or MYSQL
#
# To enabled Multiple server support
# please use MYSQL for PROVIDER, give the good information and restart the server
PROVIDER: "SQLITE"
MYSQL_database:
  host: "localhost"
  name: "FactionMaster"
  user: "root"
  pass: ""
SQLITE_database: 
  name: "FactionMasterv3"

# --------------------- GLOBAL CONFIGURATION --------------------------

# If you want to disable this feature, empty this array and reload your server
banned-faction-name: ["op", "staff", "admin", "fuck", "shit"]

xp-win-per-kill: 1
power-win-per-kill: 2
power-loose-per-death: 2
#Use to multiply the power win and loose if players are in factions
faction-multiplicator: 2
#check if player have armor equip
allow-no-stuff: false

default-home-limit: 2
default-claim-limit: 2
default-player-limit: 2
default-ally-limit: 2
# PUBLIC: 0  /  PRIVATE: 1  /  INVITATION: 2
default-faction-visibility: 0
default-faction-xp: 0
default-faction-level: 1
default-faction-description: ""
default-faction-message: ""
default-power: 0

min-faction-name-length: 3
max-faction-name-length: 20

# If it set to true, image will be display near button
# If it set to false, image will be disabled
active-image: true

faction-chat-active: false
faction-chat-symbol: "$"
faction-chat-message: "[{factionName}] {playerName}: {message}"
ally-chat-active: false
ally-chat-symbol: "%"
ally-chat-message: "[{factionName}] {playerName}: {message}"

help-command-header: "§8=§7=§8=§7=§8=§7=§8=§7=§8=§7= §bFactionMaster command §8=§7=§8=§7=§8=§7=§8=§7=§8=§7="
help-command-lign: " §8>> §r§b{command}: §7{description}"

# ------------------ BROADCAST MESSAGE CONFIGURATION ---------------------

broadcast-faction-create: false
broadcast-faction-create-message: "{playerName} has created the faction {factionName}"
broadcast-faction-delete: false
broadcast-faction-delete-message: "{playerName} has deleted the faction {factionName}"
broadcast-faction-transferProperty: false
broadcast-faction-transferProperty-message: "{playerName} transferred the property to {targetName} of the faction {factionName}"

# --------------------- F MAP CONFIGURATION -------------------------

# Set thiis value to false if you want to disable /f map on | /f map off
# Otherwise set this value to the number of ticks between each display 
f-map-task: false
#f-map-task: 40

available-symbol: ["/", "\\", "#", "$", "?", "%", "=", "&", "^", "$"]

player-symbol: "+"
player-color: "§b"

wilderness-symbol: "-"
wilderness-color: "§7" 
spawn-symbol: "-"
spawn-color: "§8" 
warzone-symbol: "-"
warzone-color: "§7" 

claim-color: "§f"
claim-ally-color: "§e"
claim-ennemie-color: "§4"
claim-own-color: "§b"

compass-color: "§c"
compass-color-actual: "§e"

map-width: 48
map-height: 10
map-header-color: "§6"
map-middle-header: ".[ §2({{x}},{{z}}) {{factionLabel}} {{headerColor}}]."

# --------------------- CLAIM CONFIGURATION --------------------------

claim-cost:
  # the type is the same type as level reward, you can put :
  #   power / allyLimit / claimLimit / homeLimit / memberLimit
  #   to make your own reward, please read the documentation
  type: "power"
  # the start value for the first claim
  value: 200

# flat: cost all the time, the same price
# addition: first claim will be cost: Ex: 100
#      second claim will be cost: Ex: 200
#      second claim will be cost: Ex: 300
# multiplication: will be times by a factor
# decrease: descrease the start value by the factor
claim-provider: "flat"
# Equation for mutliplication :
#   cost-price = cost-start * (factor ** number-claim)
multiplication-factor: 2
#Equation for decrease
#   cost-price = cost-start - (number-claim * decrease-factor)
decrease-factor: 100

# If set to false, the player cant /f sethome in a ennemy claim
allow-home-ennemy-claim: true

# --------------------- TITLE CONFIGURATION --------------------------

# Set this to true if you want to display on player's screen the message when entering a claim
message-alert: true
# The following line define which message will be print
# on the screen of players when entering a claim chunk
# active parameter which can set : {factionName} / {colorStatus} / {x} / {z} / {world}
# - colorStatus : color set in the f map configuration
# to purpose a suggestion, open an issue on our github
message-alert-title: "{colorStatus}{factionName}"
message-alert-subtitle: "{x} - {z} - {world}"
# Defines the time that will be applied before the message is displayed again
message-alert-cooldown: 10

message-alert-flag-enabled: false
# -------------- TOP FACTION'S SCOREBOARD CONFIGURATION -----------------

# SEE leaderboard.yml to enabled and updated position of the leaderboard !

# This is the scoreboard header, display on the top
faction-scoreboard-header: "- Top 10 faction -"
# Lign patern for each faction
# you can use this parameter : 
# {factionName} / {level} / {power}
# to purpose a parameter suggestion, please open an issue on github
faction-scoreboard-lign: "{factionName}: Level {level}"

# --------------------- PLUGIN CONFIGURATION --------------------------
#       DONT CHANGE IF YOU DONT KNOW WHAT YOU ARE DOING

# Change this value only if you are sure of what you are doing, 
# reducing it may break some functionality of the plugin, 
# increasing it may reduce the players experience.
# Default: 60
timeout-task: 60

# Change this value only if you are sure of what you are doing, 
# reducing it may break some functionality of the plugin, 
# increasing it may reduce the players experience.
# Default: 200
# It will determine ow much time Database synchronisation will be done
sync-time: 200

**Comment by Rtoxx** [comment]
[config.yml.txt](https://github.com/FactionMaster/FactionMaster/files/7739994/config.yml.txt)
is a config base

**Comment by ShockedPlot7560** [comment]
I will check why the addFaction return sql error statement

**Comment by Rtoxx** [comment]
okay thx
